runtime: python39

automatic_scaling:
  max_instances: 2
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 50
  min_pending_latency: 800ms

entrypoint: gunicorn -b :$PORT -k gevent -w 2 'vimhelp.webapp:create_app()'

default_expiration: "1h"

inbound_services:
- warmup

handlers:
- url: /(?:.*\.html)?
  script: auto
  secure: always
- url: /api/.+
  script: auto
  secure: always
- url: /sitemap\.txt
  script: auto
  secure: always
- url: /(?:enqueue_)?update
  script: auto
  secure: always
- url: /_ah/warmup
  script: auto
  secure: always
- url: /(.+)
  static_files: static/\1
  upload: static/(.*)
  secure: always
